### ISSUE TITLE
Must supply route to push

### ISSUE THREAD

**Issue by shirleycharlin** [caroaguilar/NavigationDrawerExample#2] opened 2016-07-15 02:01 UTC
Hi @caroaguilar (or anyone),

I followed your blog example to do a dynamic navigation drawer for my RN project. I was prompted with an error message that say "Must supply route to push".

1. I have link the drawer menus to more than one screen page.

![simulator screen shot jul 15 2016 10 00 35 am](https://cloud.githubusercontent.com/assets/17798099/16861421/046b5342-4a73-11e6-96f0-12126b10850c.png)

Thanks for helping in advance.

**Comment by caroaguilar** [comment] 2016-07-15 17:06
Hi! What do you mean by "more than one screen page"? Can I see your code please? So I can debug and help you :)

**Comment by shirleycharlin** [comment] 2016-07-18 02:56
Hey! Can just the inside of it works?

*//DrawerMenu.js*

  componentDidMount() {
      var self = this;

      _emitter.addListener('openMenu', () => {
          self._drawer.open(); //_drawer module from import Drawer from
'react-native-drawer'
      });

      _emitter.addListener('back', () => {
          self._navigator.pop();
      });

      _emitter.addListener('openSetting', () =>{
        self._drawer.open();
      })
  }


  render(){
    return (

      <Drawer
      ref={(ref) => this._drawer = ref}
      type="overlay"
      content={<Menu navigate={(route) => {
                    this._navigator.push(navigationHelper(route));
          this._drawer.close()
      }}/>}
        tapToClose={true}
        openDrawerOffset={0.2}
        panCloseMask={0.2}
        closedDrawerOffset={-3}
        styles={{
            drawer: {shadowOpacity: 0.8, shadowRadius: 3},
            main: {paddingLeft: 0.2}
        }}
        tweenHandler={(ratio) => ({
            main: { opacity:(2-ratio)/2 }
        })}>

        <Navigator
                ref={(ref) => this._navigator = ref}
                  configureScene={(route) =>
Navigator.SceneConfigs.FloatFromLeft}
                  initialRoute={{
                      id: 'Dashboard',
                      component: Dashboard,
                      index: 0
                  }}
                  renderScene={(route, navigator) =>
this._renderScene(route, navigator)}
                  navigationBar={
                      <Navigator.NavigationBar
                          routeMapper={NavigationBarRouteMapper} />
          }
          />
        </Drawer>
        );
      }

      _renderScene(route, navigator){
        switch(route.id){
          case 'MyProfile':
            return (<MyProfile navigator={navigator}/>)
          case 'MyGroups':
            return (<MyGroups navigator={navigator}/>)
          case 'MyMessages':
            return (<MyMessages navigator={navigator}/>)
          case 'MyBlogs':
            return (<MyBlogs navigator={navigator}/>)

        }
      }

}

const NavigationBarRouteMapper = {
    LeftButton(route, navigator, index, navState) {
      //var _navigator = navigator;
        switch (route.id) {
          case 'MyProfile':
              return (
                  <TouchableOpacity
                      style={styles.navBarLeftButton}
                      onPress={() => {_emitter.emit('openMenu')}}>
                      <Icon name='md-menu' size={30} color={'#000'} />
                  </TouchableOpacity>
              )
          case 'MyGroups':
              return (
                  <TouchableOpacity
                      style={styles.navBarLeftButton}
                      onPress={() => {_emitter.emit('openMenu')}}>
                      <Icon name='md-menu' size={30} color={'#000'} />
                  </TouchableOpacity>
              )
          case 'MyMessages':
              return (
                  <TouchableOpacity
                      style={styles.navBarLeftButton}
                      onPress={() => {_emitter.emit('openMenu')}}>
                      <Icon name='md-menu' size={30} color={'#000'} />
                  </TouchableOpacity>
              )
          case 'MyBlogs':
              return (
                  <TouchableOpacity
                      style={styles.navBarLeftButton}
                      onPress={() => {_emitter.emit('openMenu')}}>
                      <Icon name='md-menu' size={30} color={'#000'} />
                  </TouchableOpacity>
              )

          default:
                return (
                    <TouchableOpacity
                        style={styles.navBarLeftButton}
                        onPress={() => {_emitter.emit('openMenu')}}>
                        <Icon name='md-menu' size={30} color={'#000'} />
                    </TouchableOpacity>
                )
        }

    },

    RightButton(route, navigator, index, navState) {
        return (
            <TouchableOpacity
                style={styles.navBarRightButton}
                onPress={() =>{_emitter.emit('openSetting')}}>
                <Icon name='md-settings' size={30} color={'#000'} />
            </TouchableOpacity>
        )
    },

    Title(route, navigator, index, navState) {
        return (
            <Text style={[styles.navBarText, styles.navbarTitle]}>
                {route.title}
            </Text>
        )
    }

*//Menu.js*

var _navigate;

class Menu extends React.Component {

  constructor(props)
  {
    super(props);
    this.state = {
        dataSource: new ListView.DataSource({
            rowHasChanged: (row1, row2) => row1 !== row2
        })
    };

    _navigate = this.props.navigate;


  }

  componentDidMount()
  {
    this.setState({
        dataSource: this.state.dataSource.cloneWithRows([ 'Profile',
'Groups', 'Messages', 'Blogs'])
    });
  }

  _renderMenuItem(item) {
      return(
          <Button onPress={()=> this._onItemSelect(item)}>{item}</Button>
      );
  }

  _navigate(item){
    this.props.navigator.push({
      passProps: {
        item = route.id
      }
    })
  }

  _onItemSelect(item) {
      _navigate(item);
  }


  signOut(){
      this._navigator.push({
        id:'LogIn',
        component: LogIn
      })
    }

  render(){

    //Changes of the ListView like fontSize, fontWeight are to be change in
react-native-button/Button.js

    return (
        <View style={styles.bodyLayout}>
        <View style={styles.container}>
        <ListView
        dataSource={this.state.dataSource}
        renderRow={(item) => this._renderMenuItem(item)}
        />
        </View>
        <TouchableHighlight
        underlayColor={'transparent'}
        accessible={true}
        onPress={this.signOut.bind(this)}>
        <View style={styles.menuButton}>
          <Text style={styles.menuButtonText}>Sign Out</Text>
        </View>
        </TouchableHighlight>
        </View>
    );
  }
}

*//showPage.js*

module.exports = function (scene) {
    var componentMap = {
        'MyProfile': {
            title: 'My Profile',
            id: 'MyProfile',
            component: MyProfile
        },
        'MyGroups': {
            title: 'My Groups',
            id: 'MyGroups',
            component: MyGroups
        },
        'MyMessages': {
            title: 'My Messages',
            id: 'MyMessages',
            component: MyMessages
        },
        'MyBlogs': {
            title: 'My Blogs',
            id: 'MyBlogs',
            component: MyBlogs
        }
    }

    return componentMap[scene];
}

*Yours Sincerely,*
*Shirley *

*Blog: www.shirleycharlin.blogspot.sg
<http://www.shirleycharlin.blogspot.sg/>*

*I am a Youth.sg Campus Correspondent, representing NYP *
*https://www.youth.sg/Our-Voice/Campus-Blogs/ShirleyCharlin
<https://www.youth.sg/Our-Voice/Campus-Blogs/ShirleyCharlin> *

**Comment by shirleycharlin** [comment] 2016-07-19 00:46
@caroaguilar  I have emailed you.

**Comment by caroaguilar** [comment] 2016-07-19 00:56
yes already saw the code.

So in the `DrawerMenu.js` you have `this._navigator.push(navigationHelper(route));` but `navigationHelper` is not defined.

You have to do `import navigationHelper from 'showPage';` or using require it depends of you, but the issue is that navigationHelper is not defined so the push is getting `undefined`.

Your `showPage.js` is your helper and it's the one in charge of telling which route to push.

**Comment by shirleycharlin** [comment] 2016-07-19 01:33
Hi @caroaguilar ,

As I was waiting for your reply, I actually have it as this._navigator.push(navigationHelper(route));

imported showPage from '.../showPage.js

**Comment by caroaguilar** [comment] 2016-07-19 01:43
But then instead of `this._navigator.push(navigationHelper(route));` you should do
```
import showPage from '.../showPage.js

this._navigator.push(showPage(route));
```

**Comment by shirleycharlin** [comment] 2016-07-19 02:15
sorry @caroaguilar I actually did that. now I have another new error.

![simulator screen shot jul 19 2016 10 13 26 am](https://cloud.githubusercontent.com/assets/17798099/16936503/bf1a5e26-4d99-11e6-9d57-cad44ecab03a.png)

**Comment by caroaguilar** [comment] 2016-07-19 02:26
check the path of the file in the import statement.

**Comment by shirleycharlin** [comment] 2016-07-19 02:43
checked. It is correct.


I have make some changes to drawerMenu.js

content={<Menu navigate={(route) => {
          this._navigate.push(showPage(route));
          this._drawer.close()
      }}/>}

//cos I think it got to do with the original _navigator in this._navigator.push(showPage(route))

//after which I have an error message that says: cannot read property 'push' of undefined with the same errors as the screenshot.

//from the error message related to menu.js

  _renderMenuItem(item) {
      return(
          <Button onPress={()=> this._onItemSelect(item)}>{item}</Button>
      );
  }

  _onItemSelect(item) {
      _navigate(item);
  }

**Comment by caroaguilar** [comment] 2016-07-19 02:54
the content should be like:

```
content={<Menu navigate={(route) => {
                        this._navigator.push(navigationHelper(route));
              this._drawer.close()
          }}/>}
```

push is undefined because you are using _navigate instead of navigator.

Closing the issue since it's not an error with the code from the example.

**Closed by caroaguilar** 2016-07-19 02:54 UTC

**Comment by shirleycharlin** [comment] 2016-07-19 03:01
what about (0, showPage2.default) is not function.

**Comment by caroaguilar** [comment] 2016-07-19 03:10
That's because either showPage is undefined or the export of the module in showPage is wrong. 
Add a breakpoint using `debugger;` and debug it in Chrome Dev Tools or debug it using console.log() printing showPage variable to see its value.

**Comment by shirleycharlin** [comment] 2016-07-19 03:28
@caroaguilar  thanks you!!!! I can continue from here. Thanks you for teaching :)

**Comment by caroaguilar** [comment] 2016-07-19 03:29
@shirleycharlin perfect! Anytime! ;)

**Comment by shirleycharlin** [comment] 2016-07-19 05:54
Hi! I would like to ask if there is any _navigation function that have be configured else where besides menu.js? 

right now this is my current's error message. "_navigation is not a function "
